databases:
  - name: dpg-cu379aggph6c73bohitg-a
    databaseName: mysite_0q3c
    user: mysite
    plan: free

services:
  - type: web
    name: todo-list
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: postgresql://mysite:f6bDt628AGc7nCMIiUBux8rL8ghbzgw6@dpg-cu379aggph6c73bohitg-a/mysite_0q3c
        fromDatabase:
          name: mysite_0q3c
          property: connectionString
      - key: 9b809929f9fbbd14e581ff24ee6d526c
        sync: true
      - key: WEB_CONCURRENCY
        value: 2 # sensible default